version: '3'

services:
  tiktok-account-system:
    build: .
    container_name: tiktok-account-system
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=production
    networks:
      - tiktok-network

  nginx:
    image: nginx:latest
    container_name: tiktok-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - tiktok-account-system
    networks:
      - tiktok-network

networks:
  tiktok-network:
    driver: bridge
